name: HealthSync
options:
  bundleIdPrefix: com.healthsync
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: HealthSync
    DEVELOPMENT_LANGUAGE: es
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "1"
    INFOPLIST_FILE: HealthSync/Info.plist
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    ENABLE_PREVIEWS: YES
    SWIFT_STRICT_CONCURRENCY: complete

targets:
  HealthSync:
    type: application
    platform: iOS
    sources:
      - HealthSync
    settings:
      base:
        CODE_SIGN_STYLE: Automatic
        PRODUCT_BUNDLE_IDENTIFIER: com.healthsync.app
    info:
      path: HealthSync/Info.plist
      properties:
        CFBundleDevelopmentRegion: es
        CFBundleDisplayName: HealthSync
        CFBundleExecutable: $(EXECUTABLE_NAME)
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleInfoDictionaryVersion: "6.0"
        CFBundleName: $(PRODUCT_NAME)
        CFBundlePackageType: APPL
        CFBundleShortVersionString: "1.0.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: AccentColor
          UIImageName: LaunchImage
        UIRequiredDeviceCapabilities:
          - arm64
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSCameraUsageDescription: "HealthSync necesita acceso a la cámara para escanear recetas médicas y extraer automáticamente la información de tus medicamentos."
        NSPhotoLibraryUsageDescription: "HealthSync necesita acceso a tu galería para seleccionar fotos de recetas médicas y extraer la información de tus medicamentos."
        NSPhotoLibraryAddUsageDescription: "HealthSync necesita permiso para guardar imágenes de recetas escaneadas."
        NSUserNotificationsUsageDescription: "HealthSync envía notificaciones para recordarte cuándo tomar tus medicamentos."
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations: {}
        UIBackgroundModes:
          - remote-notification
        BGTaskSchedulerPermittedIdentifiers:
          - com.healthsync.reminders
